### ISSUE TITLE
Set Homepage tutorial is confusing/has duplicates

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#12]
https://websupport.colorado.edu/article/211-set-homepage

1. Description needs updating (See suggestion in comment below)
2. Just entering the node number in the field will not work - it needs to be a path. "node/123" is a valid path but the url path, "new-homepage" for example, will also work.  It's also confusing to tell the user to insert a number and then show a picture of inserting a word.  

Original Notes:

Is a node type the same as a content type? First time I’ve seen it called node type. Users may be confused. Also, step 2 mentions updating node number, but how would a user know what this is? Needs more clarification. Or a link to list of definitions?
Image of Settings section may need updating - not sure what displays here without other bundles being enabled.
Set homepage is in there multiple times: 
https://websupport.colorado.edu/article/211-set-homepage
https://websupport.colorado.edu/article/123-set-homepage

**Comment by kevincrafts** [comment]
Change "There may be a situation where you would like the home page to be another node type such as an article list page instead of a basic page." to "There may be a situation where you would like to change the homepage of your site to a different page."

**Comment by jbertrand** [comment]
Fix this
