### ISSUE TITLE
Add a glossary of Drupal/Web Express terms/phrases that are used in UI and Documentation

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#13]
There are some terms used in Drupal and/or Web Express that might be confusing to some users. By providing a glossary of terms the documentation will be easier to understand.

I've started a glossary here: https://websupport.colorado.edu/article/440-web-express-terms?preview=5bcdfebf042863158cc7b66f

Original Issue:
[Context](https://websupport.colorado.edu/article/212-context)
Provide info on what a node is

**Comment by ekellagher** [comment]
Glossary is here https://websupport.colorado.edu/article/430-web-express-terminology
