### ISSUE TITLE
Page Title Image

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#14]
https://websupport.colorado.edu/article/214-page-title-background

1. Explain what/why image size to use
2. Clarify what a node # is and how to get it
3. Step 2, second image needs updated. The condition section -- the node example in the Path field is incorrect - should be node/4
4. Should add image examples of the style options.

**Comment by ekellagher** [comment]
Updated tutorial
Note  image examples of the style options are displayed on demo site
