### ISSUE TITLE
Request Bundle Text

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#17]
We need some consistent boilerplate text for when a bundle is only available by request.

The text on https://websupport.colorado.edu/article/333-campus-news-feature-block says:

> Since this bundle is part of the Request bundles group, when you request this bundle a quick accessibility review of your site is made before the bundle will be ready to use. This may take thirty minutes to an hour to complete.

A bundle is available by request when we need to check that a site has an appropriate use for it - not sure an accessibility review does that.

**Comment by ekellagher** [comment]
Completed and updated
