### ISSUE TITLE
Update Articles tutorial

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#29]
https://websupport.colorado.edu/article/223-article

> Articles live in the backend of your site until they are pulled together into an Article Block or Article List Page.

This sort of makes it sound like the article isn't live until you create a article list block or article list page.

More instruction on what categories/tags are, why to use one vs the other.

**Comment by ekellagher** [comment]
updated tutorial

**Comment by cathysnider** [comment]
The Article Tutorial has been updated.
