### ISSUE TITLE
Enable Newsletter Bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#32]
https://websupport.colorado.edu/article/259-enable-newsletter-bundle

Is this even necessary? 
First, I always enable the newsletter bundle after I add it, 
Second, bundles should be enabled automatically in a future update, 
Third, I don't think we want a bunch of Enable the "NAME OF BUNDLE HERE" Bundle tutorials

**Comment by jbertrand** [comment]
I deleted this article
