### ISSUE TITLE
Add new form for requesting a training site

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#48]
https://websupport.colorado.edu/article/300-types-of-bundles

We probably don't need as many fields for a temporary site

**Comment by cathysnider** [comment]
Also, the link "requesting a 30-day test site" goes to a page titled "Website Request" with no mention that this is going to be a 30-day test site. so, just a reminder to fix this link when the new form is added.

**Comment by ekellagher** [comment]
There was already a form for requesting a testing/training site on web central - I updated the link
https://www.colorado.edu/webcentral/content/request-canvas-course-training-site
