### ISSUE TITLE
Update Table Alternatives

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#49]
https://www.colorado.edu/webcentral/tutorial/v2/layout-table-alternatives

While the example table can be improved, I don't know that is a good example of a table that should be presented in a different manner.  Whether or not the table is accessible is not the reason behind the alternative displays. The table alternatives are more about how to display the same content that does not display well on a website, particularly on tablet or mobile.

**Comment by ekellagher** [comment]
Agree this tutorial needs improvement - unpublished and removed links to this content
Will update in the future
