### ISSUE TITLE
Localist Events Block Tutorial

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#51]
https://websupport.colorado.edu/article/255-localist-events-block

1. Skip recurring events and show all instances are confusing - don’t know how to describe the difference because I’m not sure what these mean.

**Comment by ekellagher** [comment]
These explanations come from Localist Support
https://support.localist.com/widgets/
This questions has come up several times in support tickets and I would like to leave this information in the tutorial. The info in the tutorials has helped more people than it has caused tickets asking for clarification
