### ISSUE TITLE
Broken links is now under Reports and not SEO

### ISSUE THREAD

**Issue by jbertrand** [CuBoulder/express-tutorials#54]
https://websupport.colorado.edu/article/308-check-links
Verify with Kevin C if Broken links is still part of SEO bundle or just a report.

**Comment by ekellagher** [comment]
Yes - Broken links is still part of the SEO bundle - tested on a training site https://www-test.colorado.edu/p11f29298d68/admin/reports - broken links is not part of Core site and user must enable SEO bundle to see this feature
