### ISSUE TITLE
Update regions documentation

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express-tutorials#9]
https://websupport.colorado.edu/article/161-layout-regions

Image of regions is good for the Express Layout editor, but confusing for Context, as there are regions that may/may not exist.

Original notes:

May double check the first image is still accurate  - this image may be slightly confusing. Edit layout doesn’t include After Content, After Content 2 or footer and includes Title image. Is this page for Edit Layout or for Context? Should clarify. Context also names areas differently - for example Content Sidebar Left, Content Sidebar Right and Content Bottom updated image

Can blocks really be placed in the Main Content? Main Content: the content that you create while editing your page goes here. Blocks can be placed here as well, and will appear above or below the main page content depending on your settings. 

Yes you may add blocks to the main content region via context (EK) may need to clarify in what way blocks can be added to the regions. Context, Edit Layout? If including regions that are only in Context, should include all of these regions (such as Content Bottom)

**Comment by ekellagher** [comment]
updated
